//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoldMasterDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldTransfer
    {
        public int ID { get; set; }
        public string DocNo { get; set; }
        public System.DateTime TransferTime { get; set; }
        public int MoldID { get; set; }
        public int JobTypeID { get; set; }
        public Nullable<int> FromMachineID { get; set; }
        public Nullable<int> FromWorkCenterID { get; set; }
        public Nullable<int> ToMachineID { get; set; }
        public Nullable<int> ToWorkCenterID { get; set; }
    
        public virtual JobType JobType { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Machine Machine1 { get; set; }
        public virtual Mold Mold { get; set; }
        public virtual WorkCenter WorkCenter { get; set; }
        public virtual WorkCenter WorkCenter1 { get; set; }
    }
}
