//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoldMasterDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldMachine
    {
        public int ID { get; set; }
        public int MoldID { get; set; }
        public int MachineID { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<int> IsEvenRequired { get; set; }
        public Nullable<int> SetupDuration_sec { get; set; }
        public Nullable<int> CycleDuration_sec { get; set; }
        public Nullable<int> WaitDuration_sec { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Mold Mold { get; set; }
    }
}
