//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoldMasterDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldJournal
    {
        public int ID { get; set; }
        public string DocNo { get; set; }
        public int MoldID { get; set; }
        public int MachineID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int GoodPartQty { get; set; }
        public Nullable<int> ScrapPartQty { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public string ReportedBy { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Mold Mold { get; set; }
    }
}
