//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoldMasterDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoldModel()
        {
            this.Molds = new HashSet<Mold>();
        }
    
        public int ID { get; set; }
        public int MoldTypeID { get; set; }
        public string PartNo { get; set; }
        public Nullable<int> Cavity { get; set; }
        public string Description { get; set; }
        public string DesignerName { get; set; }
        public Nullable<System.DateTime> DesignDate { get; set; }
        public Nullable<int> CycleDuration_sec { get; set; }
        public Nullable<int> WaitDuration_sec { get; set; }
        public Nullable<int> ExpectedLife_units { get; set; }
    
        public virtual MoldType MoldType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mold> Molds { get; set; }
    }
}
